# Generated by Django 2.2.3 on 2019-08-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190807_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название товара'),
        ),
    ]
