# Generated by Django 2.2.3 on 2019-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190821_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='слаг'),
        ),
    ]
