# Generated by Django 2.2.3 on 2019-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190821_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='users_avatars/default.jpg', upload_to='product_images'),
        ),
    ]
