# Generated by Django 2.2.3 on 2019-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190821_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_order',
            field=models.BooleanField(default=False, verbose_name='Под заказ'),
        ),
    ]
