# Generated by Django 2.2.4 on 2019-08-25 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190825_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 20, 27, 52, 23230, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
