# Generated by Django 2.2.4 on 2019-08-27 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190826_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=38, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 21, 25, 5, 115175, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
