# Generated by Django 2.2.4 on 2019-08-27 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20190828_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='country',
            field=models.CharField(blank=True, max_length=38, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 21, 43, 17, 304335, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
