# Generated by Django 2.2 on 2019-08-31 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20190828_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 7, 48, 30, 728983, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
