# Generated by Django 2.2 on 2019-08-31 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20190831_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 10, 0, 43, 229202, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
