# Generated by Django 2.2.4 on 2019-08-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackapplication',
            name='name',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
    ]
