# Generated by Django 2.2.4 on 2019-08-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='заголовок новости')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='слаг новости')),
                ('image', models.ImageField(default='users_avatars/default.jpg', upload_to='product_images')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=128, verbose_name='автор новости')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
